[package]
name = "delete_attach_pid"
version = "0.1.0"
authors = ["Marcus Grass <marcus.grass@avanza.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
